<?php namespace ProcessWire;

class FieldtypeFileUnrenamed extends FieldtypeFile {
	
	public static function getModuleInfo() {
		return array(
			'title' => __('Files Unrenamed', __FILE__),
			'version' => '0.1.0',
			'summary' => __('Field that stores one or more unrenamed files.', __FILE__),
			'installs' => 'InputfieldFileUnrenamed'
		);
	}

	public function __construct() {
		parent::__construct();
		require_once dirname(__FILE__) . '/PagefilesUnrenamed.php';
	}

	public function getBlankValue(Page $page, Field $field) {
		$pagefiles = $this->wire(new PagefilesUnrenamed($page));
		$pagefiles->setField($field);
		$pagefiles->setTrackChanges(true);
		return $pagefiles;
	}

}

